INSERT INTO request_logs (
    timestamp,
    http_method,
    headers,
    service,
    endpoint,
    request_body,
    response_body,
    response_time_ms,
    status_code,
    user_id,
    request_id,
    client_ip,
    error_message
)
VALUES
-- Requisição rápida (sucesso)
(
    NOW(),
    'GET',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    NULL,
    '{"status": "ok"}',
    80,
    200,
    NULL,
    gen_random_uuid(),
    '192.168.0.1',
    NULL
),
-- Requisição média
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'payment-service',
    '/payment',
    '{"amount": 100}',
    '{"status": "approved"}',
    250,
    200,
    gen_random_uuid(),
    gen_random_uuid(),
    '192.168.0.2',
    NULL
),
-- Requisição lenta
(
    NOW(),
    'GET',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    NULL,
    '{"status": "ok"}',
    1200,
    200,
    NULL,
    gen_random_uuid(),
    '192.168.0.3',
    NULL
),
-- Erro interno
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'payment-service',
    '/payment',
    '{"amount": 999}',
    NULL,
    400,
    500,
    gen_random_uuid(),
    gen_random_uuid(),
    '192.168.0.4',
    '{"error": "internal server error"}'
),
-- Erro de validação
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'user-service',
    '/users',
    '{"email": "invalid"}',
    NULL,
    150,
    400,
    gen_random_uuid(),
    gen_random_uuid(),
    '192.168.0.5',
    '{"error": "invalid input"}'
),
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    '{"product_id": 1}',
    NULL,
    120,
    500,
    NULL,
    gen_random_uuid(),
    '192.168.0.2',
    '{"error": "internal_server_error", "message": "Unexpected failure"}'::jsonb
),
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    '{"product_id": 2}',
    NULL,
    140,
    502,
    NULL,
    gen_random_uuid(),
    '192.168.0.3',
    '{"error": "bad_gateway", "message": "Upstream service failed"}'::jsonb
),
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    '{"product_id": 3}',
    NULL,
    200,
    503,
    NULL,
    gen_random_uuid(),
    '192.168.0.4',
    '{"error": "service_unavailable", "message": "Service temporarily unavailable"}'::jsonb
),
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    '{"product_id": 4}',
    NULL,
    310,
    504,
    NULL,
    gen_random_uuid(),
    '192.168.0.5',
    '{"error": "timeout", "message": "Request timed out"}'::jsonb
),
(
    NOW(),
    'POST',
    '{"Content-Type": "application/json"}',
    'checkout-service',
    '/checkout',
    '{"product_id": 5}',
    NULL,
    180,
    500,
    NULL,
    gen_random_uuid(),
    '192.168.0.6',
    '{"error": "internal_server_error", "message": "Database failure"}'::jsonb
);

