"""add classification

Revision ID: 65b7badac3e6
Revises: 5372cff46ea2
Create Date: 2026-04-18 17:20:20.003506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65b7badac3e6'
down_revision: Union[str, Sequence[str], None] = '5372cff46ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_request_logs_request_id'), table_name='request_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_request_logs_request_id'), 'request_logs', ['request_id'], unique=False)
    op.drop_column('request_logs', 'classification')
    # ### end Alembic commands ###
